apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: hw-grpc-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hw-grpc-app
    spec:
      containers:
        - name: hw-grpc-container
          # This is the import path for the Go binary to build and run.
          image: ko://github.com/jonayrodriguez/sw-grpc-helloworld/cmd/helloworld
          ports:
            - name: hw-grcp
              containerPort: 50051
          env:
            - name: "GRPC_GO_LOG_VERBOSITY_LEVEL"
              value: "99"
            - name: "GRPC_GO_LOG_SEVERITY_LEVEL"
              value: "info"
            - name: "SERVER_HOST"
              value: "0.0.0.0"
         