apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-grpc
spec:
  selector:
    matchLabels:
      app: hw-grpc-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hw-grpc-app
    spec:
      containers:
        - name: hw-grpc-image
          # This is the import path for the Go binary to build and run.
          image: ko://github.com/jonayrodriguez/sw-grpc-helloworld/cmd/helloworld
          ports:
            - name: hw-grcp-api
              containerPort: 50051
              protocol: TCP
          env:
            - name: "GRPC_GO_LOG_VERBOSITY_LEVEL"
              value: "99"
            - name: "GRPC_GO_LOG_SEVERITY_LEVEL"
              value: "info"
         