apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: helloworld-ingress
  namespace: helloworld
spec:
  rules:
  - host: happy.k8s.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hw-grpc-service
            port:
              number: 50051
  tls:
    # This secret must exist beforehand
    # The cert must also contain the subj-name fortune-teller.stack.build
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/PREREQUISITES.md#tls-certificates
    - secretName: hw-tls
      hosts:
        - happy.k8s.io