apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  template:
    spec:
      containers:
        - name: hw-grpc-container
          env:
            - name: SERVER_PORT
              value: "50051"