apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-grpc
spec:
  template:
    spec:
      containers:
        - name: helloworld-grpc # (1)
          env:
            - name: CUSTOM_ENV_VARIABLE
              value: Value defined by Kustomize